### ISSUE TITLE
Question regarding slow receivers

### ISSUE THREAD

**Issue by anonymerc** [AdaptiveConsulting/Aeron.NET#59]
Hi there! Thank you for the great work done on Aeron.NET!

I am playing around with the SimplePublisher and SimpleSubscriber samples using aeron:ipc channels. In my scenario, I have 1 publisher publishing "Hello + time" every second and 4 subscribers that print to screen what they receive and then sleep for 0.5s, 1s, 1.5s and 2.5s respectively. (The sleep is to simulate slow receivers.) The first 2 subscribers are in tandem with the publisher. The slower subscriber are however showing the older messages as they try to catch up to the publisher. This is expected behavior right?

What I want though is for those slow receivers to skip to the latest messages published. I am OK with dropping old messages. Is there a way to achieve this programatically or via media-driver configuration?

**Comment by mjpt777** [comment]
Aeron is a reliable transport. With IPC it will slow down to the slowest subscriber. There is no network loss to consider.

In the network case it is possible to choose flow control strategies for multicast. The default is to go with the fastest and discard those that cannot keep up. The bundled strategies with 1.1.0 also include pacing with a preferred group of subscribers or the min of the subscribers or the max (default). 

With UDP unicast there is only one subscriber.

In the network case it is also possible to set the `reliability=false` so that loss is not recovered.

https://github.com/real-logic/Aeron/wiki/Message-Delivery-Assurances

**Comment by anonymerc** [comment]
Thanks Martin for the explanation. Now I understand it better.
